Update deploy.yml

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -50,10 +50,10 @@ env:
   UNIXNAME: "serial-studio-3.2.3"
   QML_DIR: "../../app/qml"
   PUBLISHER: "Alex Spataru"
-  INSTALL_QT_MACOS: true
-  INSTALL_QT_WINDOWS: true
-  INSTALL_QT_LINUX_INTEL: true
-  INSTALL_QT_LINUX_ARM64: true
+  INSTALL_QT_MACOS: false
+  INSTALL_QT_WINDOWS: false
+  INSTALL_QT_LINUX_INTEL: false
+  INSTALL_QT_LINUX_ARM64: false
   QTFRAMEWORK_BYPASS_LICENSE_CHECK: "true"
   DESCRIPTION: "Multi-purpose serial data visualization & processing program"
 
@@ -215,3 +215,41 @@ jobs:
 #-------------------------------------------------------------------------------
 # Create release
 #-------------------------------------------------------------------------------
+ upload:
+    name: '🗂 Create release and upload artifacts'
+    needs:
+      - build-windows
+      
+    runs-on: ubuntu-latest
+    env:
+      RELEASE_TAG: ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/tags/') && github.ref_name || 'continuous' }}
+
+    steps:
+      - name: '📥 Download artifacts'
+        uses: actions/download-artifact@v4
+        with:
+          path: ./artifacts
+          merge-multiple: true
+
+      - name: '🗑️ Delete previous release and tag if exists'
+        run: |
+          if gh release view "$RELEASE_TAG" --repo "$GITHUB_REPOSITORY" &>/dev/null; then
+            echo "Release '$RELEASE_TAG' exists. Deleting..."
+            gh release delete "$RELEASE_TAG" --cleanup-tag --yes --repo "$GITHUB_REPOSITORY" || echo "Failed to delete release. Ignoring."
+          else
+            echo "No release named '$RELEASE_TAG' found. Skipping delete."
+          fi
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+
+      - name: '🚀 Create Release'
+        uses: ncipollo/release-action@v1
+        with:
+          tag: ${{ env.RELEASE_TAG }}
+          prerelease: true
+          allowUpdates: true
+          replacesArtifacts: true
+          name: 'Continuous Build'
+          artifacts: |
+            artifacts/*.msi
+            artifacts/*.zip
